### ISSUE TITLE
Command line option to disable SSL verfication

### ISSUE THREAD

**Issue by ylue-schutzwerk** [spark1security/n0s1#14]
Is there a possiblitily to disable SSL-verification during the scan? Something similar to the `curl --insecure` flag.

**Comment by blupants** [comment]
Thank you for your suggestion. I will include it in the next release: add the "--insecure" flag to ignore SSL verification.

**Comment by ylue-schutzwerk** [comment]
Great! Thank you so much!

**Comment by blupants** [comment]
@ylue-schutzwerk Command line option to disable SSL verification is now available on the [new release version v1.0.18](https://github.com/spark1security/n0s1/releases/tag/v1.0.18)
