### ISSUE TITLE
Save findings before exiting due to keyboard interrupt

### ISSUE THREAD

**Issue by jarp0l** [spark1security/n0s1#19]
**Is your feature request related to a problem? Please describe.**
It's always frustrating when you need to interrupt the tool (e.g., due to large number of issues in Jira or having to scan many projects) and lose all the findings because the tool does not save anything before exiting.

**Describe the solution you'd like**
I would like the tool to catch keyboard interrupts (`Ctrl+C`), save the findings so far, provide user feedback about saving, and then exit gracefully with status code 130 ([ref](https://stackoverflow.com/questions/1101957/are-there-any-standard-exit-status-codes-in-linux), [ref](https://stackoverflow.com/questions/21120947/catching-keyboardinterrupt-in-python-during-program-shutdown)).

**Describe alternatives you've considered**
An alternative is to periodically save findings during the tool's execution, but this might add unnecessary overhead and complexity.

**Comment by jarp0l** [comment]
This is my implementation which I did for my use. It works as expected. Please review and maybe consider merging it if you think it's good: https://github.com/jarp0l/n0s1/commit/d76cb81a64a5dd52a4053e60eda6476f3be537fd#diff-9aa00e85cd779e2bbf09025780ba7a0c43b55846f5456d78606baa8880207a53

**Comment by jarp0l** [comment]
This is my implementation which I did for my use. It works as expected. Please review and maybe consider merging it if you think it's good: https://github.com/jarp0l/n0s1/blob/19-save-findings-on-keyboard-interrupt/src/n0s1/n0s1.py#L631-L637

I might need to move `log_message("Done!")` line to `finally` block.

**Comment by blupants** [comment]
> This is my implementation which I did for my use. It works as expected. Please review and maybe consider merging it if you think it's good: https://github.com/jarp0l/n0s1/blob/d76cb81a64a5dd52a4053e60eda6476f3be537fd/src/n0s1/n0s1.py#L631-L637
> 
> I might need to move `log_message("Done!")` line to `finally` block.

Thank you for your suggestion. It will be included in the next release.

**Comment by jarp0l** [comment]
Closing this because of #21.
