### ISSUE TITLE
n0s1 jira_scan fails due to Jira project matching reserved JQL word with error: 'JQL Query: XXX is a reserved JQL word.'

### ISSUE THREAD

**Issue by tonylomo** [spark1security/n0s1#8]
Error in the JQL Query: 'AS' is a reserved JQL word. You must surround it in quotation marks to use it in a query.

**Comment by spark1security** [comment]
> Error in the JQL Query: 'AS' is a reserved JQL word. You must surround it in quotation marks to use it in a query.

Thanks for reporting the bug. The new release v1.0.17 includes a fix for the issue.

**Comment by spark1security** [comment]
Thanks for reporting the bug. The new release v1.0.17 includes a fix for the issue.
